### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by TheColaber** [FlagClicked/FlagClicked#1]
**Is your feature request related to a problem? Please describe.**
As this project will grow, we will have more and more contributors and we need a way to credit them.

**Describe the solution you'd like**
 I think I'll need to add a new repo for new contributors as done on https://github.com/ScratchAddons/contributors. Will require [Installing the AllContributors bot](https://github.com/apps/allcontributors/installations/new), and creating a new page.

**Comment by markverb1** [comment]
Cool idea!

**Comment by markverb1** [comment]
This issue should be closed because this is now a thing.

**Comment by TheColaber** [comment]
But not the page.
