### ISSUE TITLE
ScratchBlocks Support

### ISSUE THREAD

**Issue by TheColaber** [FlagClicked/FlagClicked#16]
**Is your feature request related to a problem? Please describe.**
Tutorials will need to do their tutorials...

**Describe the solution you'd like**
In the MD, the user should be able to do this:
![image](https://user-images.githubusercontent.com/72760579/111356390-b2381600-865e-11eb-9ca3-d51df991cac3.png)

**Describe alternatives you've considered**
They could upload photos of blocks but that wouldn't be cool.

**Additional context**
https://github.com/scratchblocks/scratchblocks

**Comment by CubeyTheCube** [comment]
i'm geussing you can just insert `<script src="scratchblocks-v3.4-min.js"></script>` into the html and do something like this
```js
markdownText.replace(/\`\`\`scratchblocks\n(.*)\`\`\`/g, `<pre class="blocks">$1</pre>`)
```

**Comment by CubeyTheCube** [comment]
i'm geussing you can just insert `<script src="https://scratchblocks.github.io/js/scratchblocks-v3.4-min.js"></script>` into the html of the site, then to convert the markdown, do something like 
```js
markdownText.replace(/```scratchblocks((.|\n)*)```/g, `<pre class="blocks">$1</pre>`)
```
, then insert 
```html
<script>
scratchblocks.renderMatching('pre.blocks', {
  style:     'scratch3'
});
</script>
```
into the html
In theory this should render scratchblocks; ill make a test for it in a sec

**Comment by CubeyTheCube** [comment]
Edit: it works!!!!
https://markdownscratchblocks.cubeythecube.repl.co/

**Comment by markverb1** [comment]
> Edit: it works!!!!
> https://markdownscratchblocks.cubeythecube.repl.co/

![image](https://user-images.githubusercontent.com/77983517/111372704-a753a480-86a3-11eb-9eb6-d86b845aa8c4.png)
This is the code of the MD editor WFC uses. I don't know where to put that code you sent.

**Comment by CubeyTheCube** [comment]
ah, I see how it works

**Comment by markverb1** [comment]
> ah, I see how it works
How will we add that code then?
