### ISSUE TITLE
Verification Page

### ISSUE THREAD

**Issue by TheRykerJ** [FlagClicked/FlagClicked#21]
I know Jeffalo has a thing on Ocular that requires you to verify with a Scratch account,  and I was wondering if we could do this with When Flag Clicked or if that is even necessary.

**Comment by retronbv** [comment]
We could use fluffy scratch

**Comment by TheRykerJ** [comment]
> We could use fluffy scratch

Oh I think I have heard of that. Pretty sure that is what Ocular uses.

**Comment by TheColaber** [comment]
Duplicate of #3
