### ISSUE TITLE
Preview does not wrap

### ISSUE THREAD

**Issue by TheColaber** [FlagClicked/FlagClicked#22]
**Describe the bug**
When you type a lot of stuff in your tutorial, the preview should wrap the text ofc.

**To Reproduce**

1. Go to https://flagclicked.colabersecret.repl.co/new
2. Type so the preview overflows.

**Expected behavior**
The overflow wraps.

**Screenshots**
![image](https://user-images.githubusercontent.com/72760579/111631195-808f8e00-87c9-11eb-86e1-1f4432622ec5.png)

**Comment by markverb1** [comment]
I don't think this is happening for me
https://youtube.com/shorts/wp3DSwlra5U
