### ISSUE TITLE
XSS is a thing

### ISSUE THREAD

**Issue by TheColaber** [FlagClicked/FlagClicked#24]
yay

**Comment by markverb1** [comment]
what

**Comment by retronbv** [comment]
Noooooo

**Comment by CubeyTheCube** [comment]
isnt the markdown sanitized? how does this happen?

**Comment by TheColaber** [comment]
its not sanitized

**Comment by FunctionalMetatable** [comment]
.innerText works

**Comment by TheColaber** [comment]
No it won't for many reasons. This is an easy fix but I want there to be some flexibility.
