### ISSUE TITLE
Code blocks do not work for languages besides scratch

### ISSUE THREAD

**Issue by CubeyTheCube** [FlagClicked/FlagClicked#26]
Normally in markdown, in places like github / discord, code blocks will automatically highlight syntax,
```js
like(this);
```
However, on flagclicked this does not work.

**Comment by CubeyTheCube** [comment]
Well, you should do it for 2 reasons

  1. This is based on the scratch community, not scratch itself, so if a 8 year old wants to make a python coding tutorial, let him.
  2. No need to use some huge markdown library with syntax highlighting, just use some small syntax highlighting library ~~or bijou.js~~ and regex to do it.

**Comment by TheColaber** [comment]
1. Nope this was made for scratch tutorials.
2. Nope... it would require to work in all (or most) languages all with different syntax and bijou.js for example, can't do that.

**Comment by CubeyTheCube** [comment]
1. I think we should ask Ryker what he thinks
  2. https://craig.is/making/rainbows is only 2.5KB which isn't exactly huge, and supports the most common languages

**Comment by markverb1** [comment]
What if someone posts a tutorial on S3BRIDGE (google it) or modding scratch or something
