### ISSUE TITLE
Contributing.md's code of conduct link redirects to [name redacted] extension's version

### ISSUE THREAD

**Issue by FunctionalMetatable** [FlagClicked/FlagClicked#27]
^^^

**Comment by TheColaber** [comment]
Good Catch, but just so you know, GitHub is not scratch. You can say extension names.

**Comment by FunctionalMetatable** [comment]
> Good Catch, but just so you know, GitHub is not scratch. You can say extension names.

some scratch related repositories take off the extension names from issues so i did it just to be safe

**Comment by CubeyTheCube** [comment]
> > Good Catch, but just so you know, GitHub is not scratch. You can say extension names.
> 
> some scratch related repositories take off the extension names from issues so i did it just to be safe

Scratch addons discord bit.ly generic platformer this game is terrible

Thank you.
