### ISSUE TITLE
A "Tutorial of the day"

### ISSUE THREAD

**Issue by Genius398** [FlagClicked/FlagClicked#29]
We can have a new tutorial every day. To alert users without coming to the website, we can collect email ids and email them

**Comment by TheColaber** [comment]
> if this was implemented i think flagclicked should be on a private server instead of repl.it.

why is that?

**Comment by TheColaber** [comment]
This was technically already made if you look at the front page... It looks blank right now but won't be when tutorials actually go with a user.

**Comment by Genius398** [comment]
f
