### ISSUE TITLE
Signing in with Scratch

### ISSUE THREAD

**Issue by TheColaber** [FlagClicked/FlagClicked#3]
**Is your feature request related to a problem? Please describe.**
When new tutorials are created, they should go with the valid user who made it.

**Describe the solution you'd like**
We need a system to make sure that when creating an account, this is the actual person on scratch. We need a solution like https://ocular.jeffalo.net/login which will safely connect the scratch account to the user.

**Describe alternatives you've considered**
Not on the top of my mind, but if anyone has any, it will be considered.

**Comment by markverb1** [comment]
I think I can make it with the Scratch API pretty easily. You'll have to set your bio to a random number. There is also S4Bridge which can make a system similar to FluffyScratch Authentication.

**Comment by retronbv** [comment]
Couldn’t we use FluffyScratch?

**Comment by markverb1** [comment]
> Couldn’t we use FluffyScratch?

Is it open source?

**Comment by markverb1** [comment]
> Couldn’t we use FluffyScratch?

Yeah, forgot it was open source.

**Comment by CubeyTheCube** [comment]
I think you should authenticate with scratch, then make an account so you can log in with a new username/password. It's more convenient ~~and it makes it so ip banned users like me can use it~~

**Comment by FunctionalMetatable** [comment]
> I think you should authenticate with scratch, then make an account so you can log in with a new username/password. It's more convenient ~and it makes it so ip banned users like me can use it~

todo: make one that works like that yay

**Comment by FunctionalMetatable** [comment]
I have the backend code ready to PR but i just dont understand vue. Could I PR the backend code but not the frontend?

**Comment by TheColaber** [comment]
Sure!
