### ISSUE TITLE
custom 404 page

### ISSUE THREAD

**Issue by markverb1** [FlagClicked/FlagClicked#41]
**Is your feature request related to a problem? Please describe.**
the 404 page is really ugly and many people dont understand what `Cannot GET` means.

**Describe the solution you'd like**
add a custom 404 page.

**Comment by CubeyTheCube** [comment]
design a 404 page then ill make a pr that makes it work

**Comment by markverb1** [comment]
> design a 404 page then ill make a pr that makes it work

will be ready tommorow

**Comment by CubeyTheCube** [comment]
> > design a 404 page then ill make a pr that makes it work
> 
> will be ready tommorow

can colaber add us to the org so we can actually do stuff when hes inactive

**Comment by markverb1** [comment]
> > > design a 404 page then ill make a pr that makes it work
> > 
> > 
> > will be ready tommorow
> 
> can colaber add us to the org so we can actually do stuff when hes inactive

good idea

**Comment by TheColaber** [comment]
> can colaber add us to the org so we can actually do stuff when hes inactive

Once ya'll learn to not say useless stuff in comments (take #30 for example) and start creating some PRs.

**Comment by TheRykerJ** [comment]
I'll design a 404 page

**Comment by markverb1** [comment]
> I'll design a 404 page

Okay good, because my current 404 page design is stolen from google images.

**Comment by Steve0Greatness** [comment]
Here's what I've made:
!["this page doesn't exist" Scratch Stop Sign Image](https://i.ibb.co/0VRc77Z/Screenshot-2021-05-20-7-21-22-AM.png)

**Comment by TheRykerJ** [comment]
Hmm that gives me an idea, I'm going to try something

**Comment by markverb1** [comment]
> Here's what I've made:
> !["this page doesn't exist" Scratch Stop Sign Image](https://camo.githubusercontent.com/9d7a2e55bdc097360ff694834d50d44b8be153e35daaa6dabac4baf0c502b22e/68747470733a2f2f692e6962622e636f2f3056526337375a2f53637265656e73686f742d323032312d30352d32302d372d32312d32322d414d2e706e67)

wow, that looks great!

**Comment by TheRykerJ** [comment]
![image](https://user-images.githubusercontent.com/70858083/119001172-5dac6200-b951-11eb-8e58-90632b81586c.png)
I tried making some 404 art, but I think it's a bit cursed,  what do you guys think?

**Comment by markverb1** [comment]
> ![image](https://user-images.githubusercontent.com/70858083/119001172-5dac6200-b951-11eb-8e58-90632b81586c.png)
> I tried making some 404 art, but I think it's a bit cursed, what do you guys think?

It looks pretty good. Can you share the SVG?

**Comment by Steve0Greatness** [comment]
> ![image](https://user-images.githubusercontent.com/70858083/119001172-5dac6200-b951-11eb-8e58-90632b81586c.png)
> I tried making some 404 art, but I think it's a bit cursed, what do you guys think?

no comment.

**Comment by TheRykerJ** [comment]
Sure

https://file.io/x80xmFMOSTpk

**Comment by markverb1** [comment]
> Sure
> 
> https://file.io/x80xmFMOSTpk

uhh...
![image](https://user-images.githubusercontent.com/77983517/119001923-18aa1f00-b995-11eb-9c1b-d295b7310c39.png)

**Comment by TheRykerJ** [comment]
h mm
ok let me try a different service

**Comment by markverb1** [comment]
> h mm
> ok let me try a different service

can't you just drag it into gh?

**Comment by markverb1** [comment]
> > > h mm
> > > ok let me try a different service
> > 
> > 
> > can't you just drag it into gh?
> 
> No, apparently it doesn't support SVG

read my edit

**Comment by TheRykerJ** [comment]
Ill just publish it as a scratch project and you can take it from there. https://scratch.mit.edu/projects/533528555/

**Comment by Steve0Greatness** [comment]
![Screenshot 2021-05-20 8 04 50 AM](https://user-images.githubusercontent.com/75220768/119002844-12d71e00-b942-11eb-918d-93e533531b33.png)
uhh...

**Comment by TheRykerJ** [comment]
> ![Screenshot 2021-05-20 8 04 50 AM](https://user-images.githubusercontent.com/75220768/119002844-12d71e00-b942-11eb-918d-93e533531b33.png)
> uhh...

I have an idea to make it look better hold on

**Comment by Steve0Greatness** [comment]
> > ![Screenshot 2021-05-20 8 04 50 AM](https://user-images.githubusercontent.com/75220768/119002844-12d71e00-b942-11eb-918d-93e533531b33.png)
> > uhh...
> 
> I have an idea to make it look better hold on

ok.

**Comment by TheRykerJ** [comment]
![image](https://user-images.githubusercontent.com/70858083/119003900-b846bd80-b953-11eb-82c6-324d11897104.png)
Updated the project. Try this.

**Comment by markverb1** [comment]
![image](https://user-images.githubusercontent.com/77983517/119003644-902c7e00-b996-11eb-8ea7-792895c65af0.png)
just coded the page. click [here](https://flag-klicked-wiff-more-stuff-1.markverb4.repl.co/404) to see it

**Comment by TheRykerJ** [comment]
> ![image](https://user-images.githubusercontent.com/70858083/119003900-b846bd80-b953-11eb-82c6-324d11897104.png)
> Updated the project. Try this.

Can be downloaded from main project, might look better.

**Comment by markverb1** [comment]
looks much better
![image](https://user-images.githubusercontent.com/77983517/119004304-1ba60f00-b997-11eb-86c6-14a9d54420c6.png)

**Comment by TheRykerJ** [comment]
> looks much better
> ![image](https://user-images.githubusercontent.com/77983517/119004304-1ba60f00-b997-11eb-86c6-14a9d54420c6.png)

Could you center the text on the sign?
Then it will be perfect!

**Comment by markverb1** [comment]
done!!!!!!!!!!
![image](https://user-images.githubusercontent.com/77983517/119005452-21502480-b998-11eb-81cf-c99af403af11.png)

**Comment by TheColaber** [comment]
It would be nice to have the cat's tail be in there somewhere...

Also don't copy "scratch'ing its head"

**Comment by TheRykerJ** [comment]
Really happy with how it looks!

**Comment by Steve0Greatness** [comment]
looks cool!

**Comment by markverb1** [comment]
> It would be nice to have the cat's tail be in there somewhere...

how about this?
![image](https://user-images.githubusercontent.com/77983517/119006654-3aa5a080-b999-11eb-8b40-f9f50a3fd198.png)

**Comment by TheRykerJ** [comment]
What does it look like zoomed out?

**Comment by markverb1** [comment]
> What does it look like zoomed out?

![image](https://user-images.githubusercontent.com/77983517/119007099-9ec86480-b999-11eb-9342-940b0e4e8f94.png)
scuffed(ish).

**Comment by TheRykerJ** [comment]
Its a bit thicc, I'll try something.

**Comment by markverb1** [comment]
> Its a bit thicc, I'll try something.

![image](https://user-images.githubusercontent.com/77983517/119007404-ddf6b580-b999-11eb-8b19-7c1dfc5643b9.png)
how about this?

**Comment by TheRykerJ** [comment]
> > Its a bit thicc, I'll try something.
> 
> ![image](https://user-images.githubusercontent.com/77983517/119007404-ddf6b580-b999-11eb-8b19-7c1dfc5643b9.png)
> how about this? now it looks kinda **_t h i n n_**

Scratch cat doesn't really have a tail though, or at least it is never shown so I think we should leave it out.

**Comment by markverb1** [comment]
> > > Its a bit thicc, I'll try something.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/77983517/119007404-ddf6b580-b999-11eb-8b19-7c1dfc5643b9.png)
> > how about this? now it looks kinda **_t h i n n_**
> 
> Scratch cat doesn't really have a tail though, or at least it is never shown so I think we should leave it out.

nah, i think it looks a little better with a tale. wait lemme see how it looks in the browser

**Comment by TheRykerJ** [comment]
Well let me just say cats tails are long and thin, so maybe more like this? 
![image](https://user-images.githubusercontent.com/70858083/119008032-6738c880-b957-11eb-86d5-9c076d0bf5c3.png)

**Comment by markverb1** [comment]
![image](https://user-images.githubusercontent.com/77983517/119009369-b7397e80-b99b-11eb-8e81-c5dd2bbf55f2.png)

**Comment by TheRykerJ** [comment]
> ![image](https://user-images.githubusercontent.com/77983517/119009369-b7397e80-b99b-11eb-8e81-c5dd2bbf55f2.png)
> ![image](https://user-images.githubusercontent.com/77983517/119009780-257e4100-b99c-11eb-9c27-b4bf1c029451.png)
> 
> @TheRykerJ

Yeah that's pretty good, maybe if you could just slim it up a TINY bit more though...

**Comment by markverb1** [comment]
> > ![image](https://user-images.githubusercontent.com/77983517/119009369-b7397e80-b99b-11eb-8e81-c5dd2bbf55f2.png)
> > ![image](https://user-images.githubusercontent.com/77983517/119009780-257e4100-b99c-11eb-9c27-b4bf1c029451.png)
> > @TheRykerJ
> 
> Yeah that's pretty good, maybe if you could just slim it up a TINY bit more though...

@TheRykerJ 
![image](https://user-images.githubusercontent.com/77983517/119021541-39c83b00-b9a8-11eb-9daa-6d32f11d0abe.png)

**Comment by CubeyTheCube** [comment]
> > > ![image](https://user-images.githubusercontent.com/77983517/119009369-b7397e80-b99b-11eb-8e81-c5dd2bbf55f2.png)
> > > ![image](https://user-images.githubusercontent.com/77983517/119009780-257e4100-b99c-11eb-9c27-b4bf1c029451.png)
> > > @TheRykerJ
> > 
> > 
> > Yeah that's pretty good, maybe if you could just slim it up a TINY bit more though...
> 
> @TheRykerJ
> ![image](https://user-images.githubusercontent.com/77983517/119021541-39c83b00-b9a8-11eb-9daa-6d32f11d0abe.png)

now it just looks like an arm. I think the previous one is fine

**Comment by devxan** [comment]
@CubeyTheCube, maybe make the tail end facing upwards would look better?

**Comment by TheColaber** [comment]
lol @devxan stop self-reacting, we already know you agree and love yourself :P

**Comment by Steve0Greatness** [comment]
![It looks like the stop sign stoped us; we couldn't find the page you asked for](https://user-images.githubusercontent.com/75220768/119155351-f1406a00-ba07-11eb-9e72-04b96692db52.png)

**Comment by TheRykerJ** [comment]
Maybe it could be "Looks like you're lost, the page you are looking for doesn't exist."

**Comment by markverb1** [comment]
i added the 404 page in the nuxt version of the website. you can test it [here](https://flagclicked.markverb1.rf.gd/).
