### ISSUE TITLE
Feature Request: routes

### ISSUE THREAD

**Issue by FunctionalMetatable** [FlagClicked/FlagClicked#42]
Routes, (like fluffyscratch but nicer) would make the code much more neater

**Comment by TheColaber** [comment]
Could you explain what you mean when you say "routes"?

**Comment by FunctionalMetatable** [comment]
> Could you explain what you mean when you say "routes"?

like a module that manages all the api endpoints, taking the endpoint code from other modules

**Comment by CubeyTheCube** [comment]
this wont be necessary once this is nuxtified
