### ISSUE TITLE
Markdown Basic Syntax on the Bottom of the Editor

### ISSUE THREAD

**Issue by MusicOnStereo** [FlagClicked/FlagClicked#5]
**Is your feature request related to a problem? Please describe.**
A suggestion is all, suggested on the thought of those new to markdown...

**Describe the solution you'd like**
You could add a list of basic syntax for markdown on the bottom of the editor
(like 1 asterisk around text for *italics*, 2 asterisks around text for **bold**)

I know that you would probably just include a website link, I think it would be easier for people new to markdown if it was easily accessible at the bottom of the editor...

**Describe alternatives you've considered**
Its a pretty simple suggestion, not really any other alternatives.

**Additional stuff**
I know the editor is unfinished and early, and sorry if I suggested something that was already going to be implemented.

**Comment by markverb1** [comment]
Pretty sure colaber was already planning on doing this.
