### ISSUE TITLE
api.whenflagclicked.org

### ISSUE THREAD

**Issue by TheColaber** [FlagClicked/FlagClicked#55]
Basically move all of our APIs to a different domain. In this case... api.whenflagclicked.org

**Comment by markverb1** [comment]
ig you could create a new api (like the top secret custom status page) and change all the post requests to the new endpoints (or whatever they're called) 
###### also you mean api.whenflagclicked.*org* not api.wfc.com

**Comment by retronbv** [comment]
###### agreed

**Comment by FunctionalMetatable** [comment]
yes

**Comment by markverb1** [comment]
> yes

stop making useless comments just react with 👍

**Comment by retronbv** [comment]
> > yes
> 
> stop making useless comments just react with 👍 (same for you @retronbv)

###### no me

**Comment by CubeyTheCube** [comment]
What is the benefit of this?
