### ISSUE TITLE
Nuxtify

### ISSUE THREAD

**Issue by TheColaber** [FlagClicked/FlagClicked#57]
Nuxify.

jeffalo might not be helping much on this part, but definitely, I will try to learn some nuxt stuff and create a separate repo for this as FlagClick2.0... but won't be until we have a v1.0...

**Comment by FunctionalMetatable** [comment]
if #55 becomes real nuxtifying the website is the best way to go in my opinion

**Comment by markverb1** [comment]
Why do I feel like TC is slowly losing hope in jeffalo helping to nuxtify?

**Comment by CubeyTheCube** [comment]
we can nuxtify it ourselves, setting up a nuxt server is pretty easy

**Comment by TheColaber** [comment]
I'll be working on this here: https://github.com/FlagClicked/FlagClicked/tree/nuxt Feel free to commit to that branch once I make the initial commit

**Comment by FunctionalMetatable** [comment]
> I'll be working on this here: https://github.com/FlagClicked/FlagClicked/tree/nuxt Feel free to commit to that branch once I make the initial commit

plz can you make a new repo instead
