### ISSUE TITLE
Add "In Dev" banner.

### ISSUE THREAD

**Issue by TheRykerJ** [FlagClicked/FlagClicked#61]
**Is your feature request related to a problem? Please describe.**
I have the website linked on my signature in scratch and I don't want people going to it and seeing it not done and thinking it is just a trash site.

**Describe the solution you'd like**
Something on the homepage that says "In Development" or something like that.

**Describe alternatives you've considered**
Removing the link from my profile and the forum topic or disabling the domain until the website is ready.

**Additional context**
![image](https://user-images.githubusercontent.com/70858083/117335453-c7604280-ae60-11eb-9729-66ebb63d0e4a.png)

**Comment by FunctionalMetatable** [comment]
staging.whenflagclicked.org?

**Comment by markverb1** [comment]
Maybe a popup that will say "in development" that is only present in the main 0age?

**Comment by markverb1** [comment]
@TheRykerJ 
See #62.
