### ISSUE TITLE
Google Ads

### ISSUE THREAD

**Issue by TheRykerJ** [FlagClicked/FlagClicked#67]
Perhaps we could add Google Ads along the sides or bottoms of the pages. Like on the homepage is a good place for Google Ads. Google Ads could help fund the domain if we got enough visitors. If I remember how Google Ads works we need to have the website finished and publish first then Google will review to see if we meet requirements. 
![image](https://user-images.githubusercontent.com/70858083/117824819-68ba1080-b234-11eb-8307-13f06dc88823.png)

**Comment by TheRykerJ** [comment]
> > > dont see the point - plus, if they wanted people can just run this on their laptop using our api and would not have to watch the ads
> > 
> > 
> > You know ad blocker exists right? I don't think many people will use this on a very old laptop.
> 
> still, I'm not a fan of having ads on a scratch-affiliated website. seems kinda cheap

Possibly, but Scratch makes its money through private donors. At the moment I am the private donor of our site trying to afford everything (its not a lot but still). I see where you are coming from. We can discuss this topic further later on.

**Comment by FunctionalMetatable** [comment]
please don't monetize this site.

arc.io works fine for this sort of thing.

arc is a cdn that runs off of people's browsers, sharing bandwidth. it's pretty worth it

**Comment by TheRykerJ** [comment]
> please don't monetize this site.
> 
> arc.io works fine for this sort of thing.
> 
> arc is a cdn that runs off of people's browsers, sharing bandwidth. it's pretty worth it if you need money

Meh, with our current setup money isn't an issue, it was just an idea.
