### ISSUE TITLE
Bold text on the "Create Account" button.

### ISSUE THREAD

**Issue by TheRykerJ** [FlagClicked/FlagClicked#7]
I have a book about graphic design, and it's been a while since I have read it, but I know that you should change the "Create Account" button to **bold** so that it is more eye-catching and that is the first thing you see when you open the website.

**Comment by retronbv** [comment]
Is it just me or is the “Create Account” button not even visible?

**Comment by TheRykerJ** [comment]
> Is it just me or is the “Create Account” button not even visible?

That would be just you...
![image](https://user-images.githubusercontent.com/70858083/111183098-90b32d80-857d-11eb-9d77-3b039028e4a4.png)

**Comment by retronbv** [comment]
![1234D8D1-7EB3-4AAA-BF9F-00003057CA05](https://user-images.githubusercontent.com/49005044/111183194-0a4f1980-8586-11eb-8255-c0c5bb6be73a.jpeg)

**Comment by markverb1** [comment]
Reply to retronbv:
Try turning on desktop mode on your browser.
This might also be fixed when mobile mode becomes a thing.

**Comment by TheColaber** [comment]
Yeah, I've made it so if your screen is small, it will remove that button... my thought process was if you are on mobile, there's a bigger chance you want to log in than to create a new account. However, I can change this.

**Comment by TheRykerJ** [comment]
> Yeah, I've made it so if your screen is small, it will remove that button... my thought process was if you are on mobile, there's a bigger chance you want to log in than to create a new account. However, I can change this.

If we needed more space we could always just remove the create account button and then when you click it there will also be an option to sign in instead or vice versa.

**Comment by MusicOnStereo** [comment]
> Reply to retronbv:
> Try turning on desktop mode on your browser.
> This might also be fixed when mobile mode becomes a thing.
chromebook user here, I do not see a sign in button....

**Comment by MusicOnStereo** [comment]
> Reply to retronbv:
> Try turning on desktop mode on your browser.
> This might also be fixed when mobile mode becomes a thing.

Chromebook user here, I don't see a sign in button either.

**Comment by TheColaber** [comment]
Done in #14
