### ISSUE TITLE
Tutorial 8 Refuses to Load

### ISSUE THREAD

**Issue by Looky1173** [FlagClicked/FlagClicked#82]
**Describe the bug**
Tutorial 8 seems to be bugged as it doesn't load at all.

**To Reproduce**

1. Go to https://www.whenflagclicked.org/tutorials/8.
2. The page will say _loading..._ forever.

_OR_

1. Go to https://www.whenflagclicked.org/api/tutorials/8.
2. The request will time out.

**Expected behavior**
The tutorial should load, both when using the website and the API.

**Device Information**
- OS: Windows 10
- Browser: Google Chrome
- Version: 91

**Additional context**
_None_

**Comment by FunctionalMetatable** [comment]
strange bug.

**Comment by markverb1** [comment]
Actually, every new tutorial is broken.

**Comment by Looky1173** [comment]
@markverb1 Actually, I was able to create another tutorial and [it is not broken](https://www.whenflagclicked.org/tutorials/9).

**Comment by FunctionalMetatable** [comment]
@TheColaber could you run the following javascript in the repl:

```javascript
const Database = require("@replit/database");

const db = new Database();

db.get("tutorial-8").then(data => console.dir(data))
```
and see what comes out in the console?

**Comment by TheColaber** [comment]
Replit is giving me problems (as always :/) and it's not running the repl

**Comment by TheColaber** [comment]
![image](https://user-images.githubusercontent.com/72760579/121061814-53cc9080-c792-11eb-9526-a31a2a3d36af.png)

**Comment by FunctionalMetatable** [comment]
this?
```js
const Database = require("@replit/database");

const db = new Database();

db.get("tutorial-8", { raw: true }).then(data => console.dir(data))
```

**Comment by TheColaber** [comment]
![image](https://user-images.githubusercontent.com/72760579/121062991-c427e180-c793-11eb-8039-d9f821b03804.png)
Just so you know, we won't have this problem after nuxt and this probably some test using json instead of markdown... not a big issue...

**Comment by FunctionalMetatable** [comment]
wow thats some malformed json you've got there
