### ISSUE TITLE
vercel

### ISSUE THREAD

**Issue by FunctionalMetatable** [FlagClicked/FlagClicked#84]
I would like an action where the bot creates a vercel link on every PR... maybe you or I can create an issue on this to discuss stuff.

_Originally posted by @TheColaber in https://github.com/FlagClicked/FlagClicked/issues/83#issuecomment-856157111_

**Comment by FunctionalMetatable** [comment]
you'd have to create a vercel team (you may have to). there is a really strange and complex way to do it without though

**Comment by FunctionalMetatable** [comment]
https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project

**Comment by TheColaber** [comment]
@FunctionalMetatable Look at this repo for example... `https://github.com/benawad/dogehouse/pull/2864` I don't think they have sponsored it in any way. This is something that has to do with deployments... `https://github.com/benawad/dogehouse/deployments`

**Comment by FunctionalMetatable** [comment]
> @FunctionalMetatable Look at this repo for example... `https://github.com/benawad/dogehouse/pull/2864` I don't think they have sponsored it in any way. This is something that has to do with deployments... `https://github.com/benawad/dogehouse/deployments`

the repo is owned by a user, thus its free. if the repo is owned by an org, it wont work. vercel only supports "vercel teams" for deployments in orgs

**Comment by FunctionalMetatable** [comment]
@TheColaber did you get vercel working? my vercel doesn't deploy unless authorisation is given from members of the 'flagclicked' team
