### ISSUE TITLE
Fosshost

### ISSUE THREAD

**Issue by FunctionalMetatable** [FlagClicked/FlagClicked#96]
Can't we use fosshost for hosting the backend, and the nuxtified frontend on vercel?

**Comment by FunctionalMetatable** [comment]
cc @TheColaber

**Comment by CubeyTheCube** [comment]
https://fosshost.org/news/applications-temporarily-suspended
are you able to apply again yet?

**Comment by TheColaber** [comment]
No, as you can see. (Also, fosshost was down like 10 seconds ago XD)

**Comment by FunctionalMetatable** [comment]
https://fosshost.org/apply seems to work tho

**Comment by TheColaber** [comment]
Is works, but I don't think we will get accepted for a couple months/years

**Comment by FunctionalMetatable** [comment]
> Is works, but I don't think we will get accepted for a couple months/years

how will we launch alpha/beta?

**Comment by FunctionalMetatable** [comment]
@TheColaber I just saw https://www.openode.io/pricing, maybe that can help? We could also use replit with a hacker plan, like https://flagclicked-2.9gr.repl.co/ (its running nuxt)

**Comment by TheColaber** [comment]
Yes, I heard of openio, but the reason I left this open is because I was told that someone else had just applied for fosshost and got in. I'm not sure everything we might need for the technical specification. Specifically under the x86 VPS.

**Comment by FunctionalMetatable** [comment]
> Specifically under the x86 VPS.

true
couldn't @jeffalo help with this as he's good with servers and stuff

**Comment by TheColaber** [comment]
I'm working on choosing the best options and the things we need. I'm also going to contact them, and create a "relationship" with the compouny.

**Comment by jeffalo** [comment]
> > Specifically under the x86 VPS.
> 
> true
> couldn't @jeffalo help with this as he's good with servers and stuff

i can offer advice i guess. (im not good with servers, but i can somewhat maintain my own)

what do you need to host?

**Comment by FunctionalMetatable** [comment]
@TheColaber It looks like you can apply for Fosshost now

**Comment by TheColaber** [comment]
Yeah I started applying a couple hours ago, I think all we need is the vps right...

**Comment by TheColaber** [comment]
Fosshost has accepted my application. I'll try to get the website up and running as soon as I can.

**Comment by FunctionalMetatable** [comment]
> Fosshost has accepted my application. I'll try to get the website up and running as soon as I can.

also set up a plausible server if you can

**Comment by TheColaber** [comment]
Right now I am able to either host 2 extra small servers (1 vCPU, 1GB RAM, 8GB SSD) or 1 small server (2 vCPU, 4GB RAM, 16GB SSD). Our budget may go up later, but for now we can only have 2 servers up and running. So it's either FlagClicked and staging or FlagClicked and plausible.

**Comment by FunctionalMetatable** [comment]
maybe a staging server with production? plausible is not high prio and probably we can integrate plausible with the server middleware

**Comment by FunctionalMetatable** [comment]
@TheColaber any updates?

**Comment by TheColaber** [comment]
Not at the moment... I'm working with multiple people to get this to work how I want it... In the meantime, we can still work on issues that need to be done.

**Comment by FunctionalMetatable** [comment]
when
